### ISSUE TITLE
Hospitals are pre registered

### ISSUE THREAD

**Issue by lenalidl** [embiem/WirVsVirus#10]
where do we get the data from? 
-- Verband Uniklinikum DE (VUD) 

https://github.com/ManuelB/covid-19-vis/blob/gh-pages/germany/hospitals.geojson

ask the large channel

**Comment by Grreg** [comment]
Recommendation from #2_data_support was to use this API: https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/348b643c8b234cdc8b1b345210975b87_0?geometry=-29.859%2C46.261%2C50.913%2C55.880

Because the data looks good and is in a handy json format I will go for that.

**Comment by Grreg** [comment]
Finished with this commit: https://github.com/embiem/WirVsVirus/commit/95cbc24b3238267add0a3a652bae55040674676e

Now database can be initially filled with a csv file from the website. The API request is not finished, but not really required for this hackathon.

To import run importer_csv.py
